### Ping
GET http://localhost:3000/ping




### Recuperar todos los provedores                     v
GET http://localhost:3000/api/supplier

### Recuperar un proveedor por id
GET http://localhost:3000/api/supplier/24f3653b-3810-48ee-9ee1-d7e10d822a85
Content-Type: application/json

### Crear un proveedor
POST http://localhost:3000/api/supplier/create
Content-Type: application/json

{
  "name": "use for delete",
  "nit": "543543656"
}

### Actualziar un proveedor
PATCH http://localhost:3000/api/supplier/update
Content-Type: application/json

{
  "id": "28921146-5a76-11ee-8aed-17b8578cb9fb",
  "nit": 987987987,
  "name": "Karen Liseth con otro apellido"
}

### Delete provider
DELETE http://localhost:3000/api/supplier/delete
Content-Type: application/json

{
  "id": "2b28606d-4235-4641-8465-99ead4e35287"
}
